[build]
  publish = "dist/spa"


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/favicon.ico"
  status = 404

[[redirects]]
  from = "/favicon.png"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
